# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='This is test', max_length=255),
            preserve_default=False,
        ),
    ]
